/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template

    Dannah Janelle M. Tiamson
    BSIS-2A
    OOP FINAL OUTPUT
 */
 
package package1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.*;
import javax.swing.JOptionPane;
import java.lang.*;

/**
 *
 * @author dannah
 */
public class UserInformation extends javax.swing.JFrame {
    boolean search = true;
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
  
    /**
     * Creates new form UserInformation
     */
    public UserInformation() {
        initComponents();
        Connect();
        ui_idnumber.setText("");
        ui_idnumber.setEnabled(true);
        ui_username.setText("");
        ui_username.setEnabled(true);
        ui_firstname.setText("");
        ui_firstname.setEnabled(false);
        ui_middlename.setText("");
        ui_middlename.setEnabled(false);
        ui_lastname.setText("");
        ui_lastname.setEnabled(false);
        ui_address.setText("");
        ui_address.setEnabled(false);
        ui_mobilenum.setText("");
        ui_mobilenum.setEnabled(false);
        ui_email.setText("");
        ui_email.setEnabled(false);
        ui_password.setText("");
        ui_password.setEnabled(false);
        
        ui_updatebutton.setEnabled(false);
        
        UserInformation.this.setLocation(330, 140);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ui_idnumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ui_firstname = new javax.swing.JTextField();
        userinformation_title1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ui_username = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ui_middlename = new javax.swing.JTextField();
        ui_lastname = new javax.swing.JTextField();
        userinformation_title = new javax.swing.JLabel();
        ui_address = new javax.swing.JTextField();
        ui_updatebutton = new javax.swing.JButton();
        ui_mobilenum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ui_email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ui_closebutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ui_password = new javax.swing.JPasswordField();
        ui_search_button = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        ui_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setText("Middle Name:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel6.setText("Last Name:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel7.setText("Address:");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        userinformation_title1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        userinformation_title1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel8.setText("Mobile Number:");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ui_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_usernameActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel9.setText("Email:");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        userinformation_title.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        userinformation_title.setText("USER INFORMATION");
        userinformation_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ui_updatebutton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        ui_updatebutton.setText("Update");
        ui_updatebutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ui_updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_updatebuttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel2.setText("Username:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setText("ID Number:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ui_closebutton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        ui_closebutton.setText("Close");
        ui_closebutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ui_closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_closebuttonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("First Name:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel10.setText("Password:");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ui_search_button.setText("Search");
        ui_search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_search_buttonActionPerformed(evt);
            }
        });

        ui_delete.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        ui_delete.setText("Delete");
        ui_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userinformation_title)
                    .addComponent(userinformation_title1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(ui_mobilenum))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(ui_address))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(ui_middlename))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(ui_lastname))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ui_idnumber)
                            .addComponent(ui_firstname)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ui_username, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ui_email)
                            .addComponent(ui_password))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(ui_search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ui_closebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ui_updatebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ui_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(userinformation_title1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(userinformation_title)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ui_idnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ui_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ui_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ui_middlename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ui_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(ui_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(ui_mobilenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ui_updatebutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ui_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(ui_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(ui_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ui_closebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(ui_search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ui_updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        int answer;
        answer = JOptionPane.showConfirmDialog(null, "Are you sure you want to update this record?", "System Message", JOptionPane.YES_NO_OPTION);
        
        if(answer == JOptionPane.YES_OPTION){
            try{
                ui_delete.setEnabled(false);
                Connection cn;
                Statement st;
                String url;
                url = "jdbc:mysql://localhost:3306/isdb";
                Class.forName("com.mysql.cj.jdbc.Driver");
                cn = (Connection) DriverManager.getConnection(url, "root", "5432112345");
                st = (Statement) cn.createStatement();
                
                st.executeUpdate("UPDATE login_tbl SET FIRSTNAME= '" 
                        +ui_firstname.getText()+"', MIDDLENAME= '"
                        +ui_middlename.getText()+"' LASTNAME= '"
                        +ui_lastname.getText()+"', ADDRESS= '"
                        +ui_address.getText()+"', MOBILENUMBER= '"
                        +ui_mobilenum.getText()+"', EMAIL= '"
                        +ui_email.getText()+"', PASSWORD= '"
                        +ui_password.getText()
                        +"'Where IDNUMBER = "
                        
                        +ui_idnumber.getText() + "'");
                JOptionPane.showMessageDialog(null, "Record Updated", "System Message",JOptionPane.INFORMATION_MESSAGE);
             
                ui_firstname.setText("");
                ui_middlename.setText("");
                ui_lastname.setText("");
                ui_address.setText("");
                ui_mobilenum.setText("");
                ui_email.setEnabled(false);
                ui_password.setText("");
           
        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(frameTerminateEdit.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            //Logger.getLogger(frameTerminateEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }                                          

    private void ui_deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed
 
    
    //search
    public void Connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/isdb","root","5432112345");
            
        } catch (ClassNotFoundException ex) {
          
        } catch (SQLException ex) {
          
        }
    }
 
    private void ui_closebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_closebuttonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ui_closebuttonActionPerformed

    private void ui_search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_search_buttonActionPerformed
       try {      
            pst = con.prepareStatement("select IDNUMBER,FIRSTNAME, MIDDLENAME, LASTNAME, ADDRESS, MOBILENUMBER, EMAIL, PASSWORD from login_tbl where IDNUMBER =? ");
            int id = Integer.parseInt(ui_idnumber.getText());
            pst.setInt(1, id);
            ResultSet rs1 = pst.executeQuery();
            if(rs1.next()==false){
                JOptionPane.showMessageDialog(this, "Sorry Record Not Found");
                              
                ui_firstname.setText("");
                ui_middlename.setText("");
                ui_lastname.setText("");
                ui_address.setText("");
                ui_mobilenum.setText("");
                ui_email.setText("");
                ui_password.setText("");
                                
                ui_idnumber.requestFocus();
                
                }else{

            ui_firstname.setText(rs1.getString("FIRSTNAME"));
                        ui_middlename.setText(rs1.getString("MIDDLENAME"));
                         ui_lastname.setText(rs1.getString("LASTNAME"));
                          ui_address.setText(rs1.getString("ADDRESS"));
                           ui_mobilenum.setText(rs1.getString("MOBILENUMBER"));
                            ui_email.setText(rs1.getString("EMAIL"));
                             ui_password.setText(rs1.getString("PASSWORD"));
                               ui_updatebutton.setEnabled(true);
                }
            
        } catch (SQLException ex) {
            //Logger.getLogger(SearchJdbc.class.getName()).log(Level.SEVERE, null, ex);
        
        }
    }//GEN-LAST:event_ui_search_buttonActionPerformed

    private void ui_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ui_usernameActionPerformed

    private void ui_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_deleteActionPerformed
      int answer;
        answer = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this record?","System Message",JOptionPane.YES_NO_OPTION);
        if(answer==JOptionPane.YES_OPTION){
            try {
            Connection cn;
            Statement st;
            String url;

            url = "jdbc:mysql://localhost:3306/isdb";
            cn = (Connection) DriverManager.getConnection(url, "root", "5432112345");
            st = (Statement) cn.createStatement();
         
            st.executeUpdate("UPDATE login_tbl SET  FIRSTNAME= '"+ui_firstname.getText()+
                     "',MIDDLENAME= '"+ui_middlename.getText()+
                     "',LASTNAME= '"+ui_lastname.getText()+
                     "',ADDRESS= '"+ui_address.getText()+
                     "',MOBILENUMBER = '"+ui_mobilenum.getText()+
                     "',EMAIL = '"+ui_email.getText()+
                     "',PASSWORD = '"+ui_password.getText()+
                     "'WHERE IDNUMBER = '"+ui_idnumber.getText()+"' ");

                String query;
                query = "Delete From login_tbl Where ID ='" + ui_idnumber.getText() + "'";
                st.executeUpdate(query);
                
                JOptionPane.showMessageDialog(null, "Record Deleted","System Message",JOptionPane.INFORMATION_MESSAGE);
                 
                ui_firstname.setText("");
                ui_middlename.setText("");
                ui_lastname.setText("");
                ui_address.setText("");
                ui_mobilenum.setText("");
                ui_email.setText("");
                ui_password.setText("");
            
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_ui_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField ui_address;
    private javax.swing.JButton ui_closebutton;
    private javax.swing.JButton ui_delete;
    private javax.swing.JTextField ui_email;
    private javax.swing.JTextField ui_firstname;
    private javax.swing.JTextField ui_idnumber;
    private javax.swing.JTextField ui_lastname;
    private javax.swing.JTextField ui_middlename;
    private javax.swing.JTextField ui_mobilenum;
    private javax.swing.JPasswordField ui_password;
    private javax.swing.JButton ui_search_button;
    private javax.swing.JButton ui_updatebutton;
    private javax.swing.JTextField ui_username;
    private javax.swing.JLabel userinformation_title;
    private javax.swing.JLabel userinformation_title1;
    // End of variables declaration//GEN-END:variables
}
